name: RIABandwidthSaver-PE
version: '${project.version}'
main: com.mangocraft.plugins.riabandwidthsaverpe.RIABandwidthSaver
api-version: '1.21'
folia-supported: true
author: Mangocraft
depend:
  - packetevents
permissions:
  riabandwidthsaver.bypass:
    description: Player will not enter AFK mode
    default: false
  riabandwidthsaver.admin:
    description: Allows access to admin commands
    default: op
commands:
  riabandwidthsaver:
    usage: /riabandwidthsaver
    permission: riabandwidthsaver.admin
    permission-message: You don't have permission to use this command! <permission>